<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateKankensTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kankens', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->string('nama');
            $table->string('noengine')->unique();
            $table->string('shift');
            $table->date('tanggal');
            $table->char('customCheckbox1', 3)->default('0')->nullable();
            $table->char('customCheckbox2', 3)->default('0')->nullable();
            $table->char('customCheckbox3', 3)->default('0')->nullable();
            $table->char('customCheckbox4', 3)->default('0')->nullable();
            $table->char('customCheckbox5', 3)->default('0')->nullable();
            $table->char('customCheckbox6', 3)->default('0')->nullable();
            $table->char('customCheckbox7', 3)->default('0')->nullable();
            $table->char('customCheckbox8', 3)->default('0')->nullable();
            $table->char('customCheckbox9', 3)->default('0')->nullable();
            $table->char('customCheckbox10', 3)->default('0')->nullable();
            $table->char('customCheckbox11', 3)->default('0')->nullable();
            $table->char('customCheckbox12', 3)->default('0')->nullable();
            $table->char('customCheckbox13', 3)->default('0')->nullable();
            $table->char('customCheckbox14', 3)->default('0')->nullable();
            $table->char('customCheckbox15', 3)->default('0')->nullable();
            $table->char('customCheckbox16', 3)->default('0')->nullable();
            $table->char('customCheckbox17', 3)->default('0')->nullable();
            $table->char('customCheckbox18', 3)->default('0')->nullable();
            $table->char('customCheckbox19', 3)->default('0')->nullable();
            $table->char('customCheckbox20', 3)->default('0')->nullable();
            $table->char('customCheckbox21', 3)->default('0')->nullable();
            $table->char('customCheckbox22', 3)->default('0')->nullable();
            $table->char('customCheckbox23', 3)->default('0')->nullable();
            $table->char('customCheckbox24', 3)->default('0')->nullable();
            $table->char('customCheckbox25', 3)->default('0')->nullable();
            $table->char('customCheckbox26', 3)->default('0')->nullable();
            $table->char('customCheckbox27', 3)->default('0')->nullable();
            $table->char('customCheckbox28', 3)->default('0')->nullable();
            $table->char('customCheckbox29', 3)->default('0')->nullable();
            $table->char('customCheckbox30', 3)->default('0')->nullable();
            $table->char('customCheckbox31', 3)->default('0')->nullable();
            $table->char('customCheckbox32', 3)->default('0')->nullable();
            $table->char('customCheckbox33', 3)->default('0')->nullable();
            $table->char('customCheckbox34', 3)->default('0')->nullable();
            $table->char('customCheckbox35', 3)->default('0')->nullable();
            $table->char('customCheckbox36', 3)->default('0')->nullable();
            $table->char('customCheckbox37', 3)->default('0')->nullable();
            $table->char('customCheckbox38', 3)->default('0')->nullable();
            $table->char('customCheckbox39', 3)->default('0')->nullable();
            $table->char('customCheckbox40', 3)->default('0')->nullable();
            $table->char('customCheckbox41', 3)->default('0')->nullable();
            $table->char('customCheckbox42', 3)->default('0')->nullable();
            $table->char('customCheckbox43', 3)->default('0')->nullable();
            $table->char('customCheckbox44', 3)->default('0')->nullable();
            $table->char('customCheckbox45', 3)->default('0')->nullable();
            $table->char('customCheckbox46', 3)->default('0')->nullable();
            $table->char('customCheckbox47', 3)->default('0')->nullable();
            $table->char('customCheckbox48', 3)->default('0')->nullable();
            $table->char('customCheckbox49', 3)->default('0')->nullable();
            $table->char('customCheckbox50', 3)->default('0')->nullable();
            $table->char('customCheckbox51', 3)->default('0')->nullable();
            $table->char('customCheckbox52', 3)->default('0')->nullable();
            $table->char('customCheckbox53', 3)->default('0')->nullable();
            $table->char('customCheckbox54', 3)->default('0')->nullable();
            $table->char('customCheckbox55', 3)->default('0')->nullable();
            $table->char('customCheckbox56', 3)->default('0')->nullable();
            $table->char('customCheckbox57', 3)->default('0')->nullable();
            $table->char('customCheckbox58', 3)->default('0')->nullable();
            $table->char('customCheckbox59', 3)->default('0')->nullable();
            $table->char('customCheckbox60', 3)->default('0')->nullable();
            $table->char('customCheckbox61', 3)->default('0')->nullable();
            $table->char('customCheckbox62', 3)->default('0')->nullable();
            $table->char('customCheckbox63', 3)->default('0')->nullable();
            $table->char('customCheckbox64', 3)->default('0')->nullable();
            $table->char('customCheckbox65', 3)->default('0')->nullable();
            $table->char('customCheckbox66', 3)->default('0')->nullable();
            $table->char('customCheckbox67', 3)->default('0')->nullable();
            $table->char('customCheckbox68', 3)->default('0')->nullable();
            $table->char('customCheckbox69', 3)->default('0')->nullable();
            $table->char('customCheckbox70', 3)->default('0')->nullable();
            $table->char('customCheckbox71', 3)->default('0')->nullable();
            $table->char('customCheckbox72', 3)->default('0')->nullable();
            $table->char('customCheckbox73', 3)->default('0')->nullable();
            $table->char('customCheckbox74', 3)->default('0')->nullable();
            $table->char('customCheckbox75', 3)->default('0')->nullable();
            $table->char('customCheckbox76', 3)->default('0')->nullable();
            $table->char('customCheckbox77', 3)->default('0')->nullable();
            $table->char('customCheckbox78', 3)->default('0')->nullable();
            $table->char('customCheckbox79', 3)->default('0')->nullable();
            $table->char('customCheckbox80', 3)->default('0')->nullable();
            $table->char('customCheckbox81', 3)->default('0')->nullable();
            $table->char('customCheckbox82', 3)->default('0')->nullable();
            $table->char('customCheckbox83', 3)->default('0')->nullable();
            $table->char('customCheckbox84', 3)->default('0')->nullable();
            $table->char('customCheckbox85', 3)->default('0')->nullable();
            $table->char('customCheckbox86', 3)->default('0')->nullable();
            $table->char('customCheckbox87', 3)->default('0')->nullable();
            $table->char('customCheckbox88', 3)->default('0')->nullable();
            $table->char('customCheckbox89', 3)->default('0')->nullable();
            $table->char('customCheckbox90', 3)->default('0')->nullable();
            $table->char('customCheckbox91', 3)->default('0')->nullable();
            $table->char('customCheckbox92', 3)->default('0')->nullable();
            $table->char('customCheckbox93', 3)->default('0')->nullable();
            $table->char('customCheckbox94', 3)->default('0')->nullable();
            $table->char('customCheckbox95', 3)->default('0')->nullable();
            $table->char('customCheckbox96', 3)->default('0')->nullable();
            $table->char('customCheckbox97', 3)->default('0')->nullable();
            $table->char('customCheckbox98', 3)->default('0')->nullable();
            $table->char('customCheckbox99', 3)->default('0')->nullable();
            $table->char('customCheckbox100', 3)->default('0')->nullable();
            $table->char('customCheckbox101', 3)->default('0')->nullable();
            $table->char('customCheckbox102', 3)->default('0')->nullable();
            $table->char('customCheckbox103', 3)->default('0')->nullable();
            $table->char('customCheckbox104', 3)->default('0')->nullable();
            $table->char('customCheckbox105', 3)->default('0')->nullable();
            $table->char('customCheckbox106', 3)->default('0')->nullable();
            $table->char('customCheckbox107', 3)->default('0')->nullable();
            $table->char('customCheckbox108', 3)->default('0')->nullable();
            $table->char('customCheckbox109', 3)->default('0')->nullable();
            $table->char('customCheckbox110', 3)->default('0')->nullable();
            $table->char('customCheckbox111', 3)->default('0')->nullable();
            $table->char('customCheckbox112', 3)->default('0')->nullable();
            $table->char('customCheckbox113', 3)->default('0')->nullable();
            $table->char('customCheckbox114', 3)->default('0')->nullable();
            $table->char('customCheckbox115', 3)->default('0')->nullable();
            $table->char('customCheckbox116', 3)->default('0')->nullable();
            $table->char('customCheckbox117', 3)->default('0')->nullable();
            $table->char('customCheckbox118', 3)->default('0')->nullable();
            $table->char('customCheckbox119', 3)->default('0')->nullable();
            $table->char('customCheckbox120', 3)->default('0')->nullable();
            $table->char('customCheckbox121', 3)->default('0')->nullable();
            $table->char('customCheckbox122', 3)->default('0')->nullable();
            $table->char('customCheckbox123', 3)->default('0')->nullable();
            $table->char('customCheckbox124', 3)->default('0')->nullable();
            $table->char('customCheckbox125', 3)->default('0')->nullable();
            $table->char('customCheckbox126', 3)->default('0')->nullable();
            $table->char('customCheckbox127', 3)->default('0')->nullable();
            $table->char('customCheckbox128', 3)->default('0')->nullable();
            $table->char('customCheckbox129', 3)->default('0')->nullable();
            $table->char('customCheckbox130', 3)->default('0')->nullable();
            $table->char('customCheckbox131', 3)->default('0')->nullable();
            $table->char('customCheckbox132', 3)->default('0')->nullable();
            $table->char('customCheckbox133', 3)->default('0')->nullable();
            $table->char('customCheckbox134', 3)->default('0')->nullable();
            $table->char('customCheckbox135', 3)->default('0')->nullable();
            $table->char('customCheckbox136', 3)->default('0')->nullable();
            $table->char('customCheckbox137', 3)->default('0')->nullable();
            $table->char('customCheckbox138', 3)->default('0')->nullable();
            $table->char('customCheckbox139', 3)->default('0')->nullable();
            $table->char('customCheckbox140', 3)->default('0')->nullable();
            $table->char('customCheckbox141', 3)->default('0')->nullable();
            $table->char('customCheckbox142', 3)->default('0')->nullable();
            $table->char('customCheckbox143', 3)->default('0')->nullable();
            $table->char('customCheckbox144', 3)->default('0')->nullable();
            $table->char('customCheckbox145', 3)->default('0')->nullable();
            $table->char('customCheckbox146', 3)->default('0')->nullable();
            $table->char('customCheckbox147', 3)->default('0')->nullable();
            $table->char('customCheckbox148', 3)->default('0')->nullable();
            $table->char('customCheckbox149', 3)->default('0')->nullable();
            $table->char('customCheckbox150', 3)->default('0')->nullable();
            $table->char('customCheckbox151', 3)->default('0')->nullable();
            $table->char('customCheckbox152', 3)->default('0')->nullable();
            $table->char('customCheckbox153', 3)->default('0')->nullable();
            $table->char('customCheckbox154', 3)->default('0')->nullable();
            $table->char('customCheckbox155', 3)->default('0')->nullable();
            $table->char('customCheckbox156', 3)->default('0')->nullable();
            $table->char('customCheckbox157', 3)->default('0')->nullable();
            $table->char('customCheckbox158', 3)->default('0')->nullable();
            $table->char('customCheckbox159', 3)->default('0')->nullable();
            $table->char('customCheckbox160', 3)->default('0')->nullable();
            $table->char('customCheckbox161', 3)->default('0')->nullable();
            $table->char('customCheckbox162', 3)->default('0')->nullable();
            $table->char('customCheckbox163', 3)->default('0')->nullable();
            $table->char('customCheckbox164', 3)->default('0')->nullable();
            $table->char('customCheckbox165', 3)->default('0')->nullable();
            $table->char('customCheckbox166', 3)->default('0')->nullable();
            $table->char('customCheckbox167', 3)->default('0')->nullable();
            $table->char('customCheckbox168', 3)->default('0')->nullable();
            $table->char('customCheckbox169', 3)->default('0')->nullable();
            $table->char('customCheckbox170', 3)->default('0')->nullable();
            $table->char('customCheckbox171', 3)->default('0')->nullable();
            $table->char('customCheckbox172', 3)->default('0')->nullable();
            $table->char('customCheckbox173', 3)->default('0')->nullable();
            $table->char('customCheckbox174', 3)->default('0')->nullable();
            $table->char('customCheckbox175', 3)->default('0')->nullable();
            $table->char('customCheckbox176', 3)->default('0')->nullable();
            $table->char('customCheckbox177', 3)->default('0')->nullable();
            $table->char('customCheckbox178', 3)->default('0')->nullable();
            $table->char('customCheckbox179', 3)->default('0')->nullable();
            $table->char('customCheckbox180', 3)->default('0')->nullable();
            $table->char('customCheckbox181', 3)->default('0')->nullable();
            $table->char('customCheckbox182', 3)->default('0')->nullable();
            $table->char('customCheckbox183', 3)->default('0')->nullable();
            $table->char('customCheckbox184', 3)->default('0')->nullable();
            $table->char('customCheckbox185', 3)->default('0')->nullable();
            $table->char('customCheckbox186', 3)->default('0')->nullable();
            $table->char('customCheckbox187', 3)->default('0')->nullable();
            $table->char('customCheckbox188', 3)->default('0')->nullable();
            $table->char('customCheckbox189', 3)->default('0')->nullable();
            $table->char('customCheckbox190', 3)->default('0')->nullable();
            $table->char('customCheckbox191', 3)->default('0')->nullable();
            $table->char('customCheckbox192', 3)->default('0')->nullable();
            $table->char('customCheckbox193', 3)->default('0')->nullable();
            $table->char('customCheckbox194', 3)->default('0')->nullable();
            $table->char('customCheckbox195', 3)->default('0')->nullable();
            $table->char('customCheckbox196', 3)->default('0')->nullable();
            $table->char('customCheckbox197', 3)->default('0')->nullable();
            $table->char('customCheckbox198', 3)->default('0')->nullable();
            $table->char('customCheckbox199', 3)->default('0')->nullable();
            $table->char('customCheckbox200', 3)->default('0')->nullable();
            $table->char('customCheckbox201', 3)->default('0')->nullable();
            $table->char('customCheckbox202', 3)->default('0')->nullable();
            $table->char('customCheckbox203', 3)->default('0')->nullable();
            $table->char('customCheckbox204', 3)->default('0')->nullable();
            $table->char('customCheckbox205', 3)->default('0')->nullable();
            $table->char('customCheckbox206', 3)->default('0')->nullable();
            $table->char('customCheckbox207', 3)->default('0')->nullable();
            $table->char('customCheckbox208', 3)->default('0')->nullable();
            $table->char('customCheckbox209', 3)->default('0')->nullable();
            $table->char('customCheckbox210', 3)->default('0')->nullable();
            $table->char('customCheckbox211', 3)->default('0')->nullable();
            $table->char('customCheckbox212', 3)->default('0')->nullable();
            $table->char('customCheckbox213', 3)->default('0')->nullable();
            $table->char('customCheckbox214', 3)->default('0')->nullable();
            $table->char('customCheckbox215', 3)->default('0')->nullable();
            $table->char('customCheckbox216', 3)->default('0')->nullable();
            $table->char('customCheckbox217', 3)->default('0')->nullable();
            $table->char('customCheckbox218', 3)->default('0')->nullable();
            $table->char('customCheckbox219', 3)->default('0')->nullable();
            $table->char('customCheckbox220', 3)->default('0')->nullable();
            $table->char('customCheckbox221', 3)->default('0')->nullable();
            $table->char('customCheckbox222', 3)->default('0')->nullable();
            $table->char('customCheckbox223', 3)->default('0')->nullable();
            $table->char('customCheckbox224', 3)->default('0')->nullable();
            $table->char('customCheckbox225', 3)->default('0')->nullable();
            $table->char('customCheckbox226', 3)->default('0')->nullable();
            $table->char('customCheckbox227', 3)->default('0')->nullable();
            $table->char('customCheckbox228', 3)->default('0')->nullable();
            $table->char('customCheckbox229', 3)->default('0')->nullable();
            $table->char('customCheckbox230', 3)->default('0')->nullable();
            $table->char('customCheckbox231', 3)->default('0')->nullable();
            $table->char('customCheckbox232', 3)->default('0')->nullable();
            $table->char('customCheckbox233', 3)->default('0')->nullable();
            $table->char('customCheckbox234', 3)->default('0')->nullable();
            $table->char('customCheckbox235', 3)->default('0')->nullable();
            $table->char('customCheckbox236', 3)->default('0')->nullable();
            $table->char('customCheckbox237', 3)->default('0')->nullable();
            $table->char('customCheckbox238', 3)->default('0')->nullable();
            $table->char('customCheckbox239', 3)->default('0')->nullable();
            $table->char('customCheckbox240', 3)->default('0')->nullable();
            $table->char('customCheckboxTorqueBolt', 3)->default('0')->nullable();
            $table->char('customCheckboxWasher', 3)->default('0')->nullable();
            $table->char('customCheckboxSwitchOil', 3)->default('0')->nullable();
            $table->integer('act1')->nullable();
            $table->integer('act2')->nullable();
            $table->integer('act3')->nullable();
            $table->integer('act4')->nullable();
            $table->integer('act5')->nullable();
            $table->integer('act6')->nullable();
            $table->integer('act7')->nullable();
            $table->integer('act8')->nullable();
            $table->integer('act9')->nullable();
            $table->integer('act10')->nullable();
            $table->integer('act11')->nullable();
            $table->integer('act12')->nullable();
            $table->integer('act13')->nullable();
            $table->integer('act14')->nullable();
            $table->integer('act15')->nullable();
            $table->integer('act16')->nullable();
            $table->integer('act17')->nullable();
            $table->integer('act18')->nullable();
            $table->integer('act19')->nullable();
            $table->integer('act20')->nullable();
            $table->integer('act21')->nullable();
            $table->integer('act22')->nullable();
            $table->integer('act23')->nullable();
            $table->integer('act24')->nullable();
            $table->integer('act25')->nullable();
            $table->integer('act26')->nullable();
            $table->integer('act27')->nullable();
            $table->integer('act28')->nullable();
            $table->integer('act29')->nullable();
            $table->integer('act30')->nullable();
            $table->integer('act31')->nullable();
            $table->integer('act32')->nullable();
            $table->integer('act33')->nullable();
            $table->integer('act34')->nullable();
            $table->integer('act35')->nullable();
            $table->integer('act36')->nullable();
            $table->integer('act37')->nullable();
            $table->integer('act38')->nullable();
            $table->integer('act39')->nullable();
            $table->integer('act40')->nullable();
            $table->integer('act41')->nullable();
            $table->integer('act42')->nullable();
            $table->integer('act43')->nullable();
            $table->integer('act44')->nullable();
            $table->integer('act45')->nullable();
            $table->integer('act46')->nullable();
            $table->integer('act47')->nullable();
            $table->integer('act48')->nullable();
            $table->integer('act49')->nullable();
            $table->integer('act50')->nullable();
            $table->integer('act51')->nullable();
            $table->integer('act52')->nullable();
            $table->integer('act53')->nullable();
            $table->integer('act54')->nullable();
            $table->integer('act55')->nullable();
            $table->integer('act56')->nullable();
            $table->integer('act57')->nullable();
            $table->integer('act58')->nullable();
            $table->integer('act59')->nullable();
            $table->integer('act60')->nullable();
            $table->integer('act61')->nullable();
            $table->integer('act62')->nullable();
            $table->integer('act63')->nullable();
            $table->integer('act64')->nullable();
            $table->integer('act65')->nullable();
            $table->integer('act66')->nullable();
            $table->integer('act67')->nullable();
            $table->integer('act68')->nullable();
            $table->integer('act69')->nullable();
            $table->integer('act70')->nullable();
            $table->integer('act71')->nullable();
            $table->integer('act72')->nullable();
            $table->integer('act73')->nullable();
            $table->integer('act74')->nullable();
            $table->integer('act75')->nullable();
            $table->integer('act76')->nullable();
            $table->integer('act77')->nullable();
            $table->integer('act78')->nullable();
            $table->integer('act79')->nullable();
            $table->integer('act80')->nullable();
            $table->integer('act81')->nullable();
            $table->integer('act82')->nullable();
            $table->integer('act83')->nullable();
            $table->integer('act84')->nullable();
            $table->integer('act85')->nullable();
            $table->integer('act86')->nullable();
            $table->integer('act87')->nullable();
            $table->integer('act88')->nullable();
            $table->integer('act89')->nullable();
            $table->integer('act90')->nullable();
            $table->integer('act91')->nullable();
            $table->integer('act92')->nullable();
            $table->integer('act93')->nullable();
            $table->integer('act94')->nullable();
            $table->integer('act95')->nullable();
            $table->integer('act96')->nullable();
            $table->integer('act97')->nullable();
            $table->integer('act98')->nullable();
            $table->integer('act99')->nullable();
            $table->integer('act100')->nullable();
            $table->integer('act101')->nullable();
            $table->integer('act102')->nullable();
            $table->integer('act103')->nullable();
            $table->integer('act104')->nullable();
            $table->integer('act105')->nullable();
            $table->integer('act106')->nullable();
            $table->integer('act107')->nullable();
            $table->integer('act108')->nullable();
            $table->integer('act109')->nullable();
            $table->integer('act110')->nullable();
            $table->integer('act111')->nullable();
            $table->integer('act112')->nullable();
            $table->integer('act113')->nullable();
            $table->integer('act114')->nullable();
            $table->integer('act115')->nullable();
            $table->integer('act116')->nullable();
            $table->integer('act117')->nullable();
            $table->integer('act118')->nullable();
            $table->integer('act119')->nullable();
            $table->integer('act120')->nullable();
            $table->integer('act121')->nullable();
            $table->integer('act122')->nullable();
            $table->integer('act123')->nullable();
            $table->integer('act124')->nullable();
            $table->integer('act125')->nullable();
            $table->integer('act126')->nullable();
            $table->integer('act127')->nullable();
            $table->integer('act128')->nullable();
            $table->integer('act129')->nullable();
            $table->integer('act130')->nullable();
            $table->integer('act131')->nullable();
            $table->integer('act132')->nullable();
            $table->integer('act133')->nullable();
            $table->integer('act134')->nullable();
            $table->integer('act135')->nullable();
            $table->integer('act136')->nullable();
            $table->integer('act137')->nullable();
            $table->integer('act138')->nullable();
            $table->integer('act139')->nullable();
            $table->integer('act140')->nullable();
            $table->integer('act141')->nullable();
            $table->integer('act142')->nullable();
            $table->integer('act143')->nullable();
            $table->integer('act144')->nullable();
            $table->integer('act145')->nullable();
            $table->integer('act146')->nullable();
            $table->integer('act147')->nullable();
            $table->integer('act148')->nullable();
            $table->integer('act149')->nullable();
            $table->integer('act150')->nullable();
            $table->integer('act151')->nullable();
            $table->integer('act152')->nullable();
            $table->integer('act153')->nullable();
            $table->integer('act154')->nullable();
            $table->integer('act155')->nullable();
            $table->integer('act156')->nullable();
            $table->integer('act157')->nullable();
            $table->integer('act158')->nullable();
            $table->integer('act159')->nullable();
            $table->integer('act160')->nullable();
            $table->integer('act161')->nullable();
            $table->integer('act162')->nullable();
            $table->integer('act163')->nullable();
            $table->integer('act164')->nullable();
            $table->integer('act165')->nullable();
            $table->integer('act166')->nullable();
            $table->integer('act167')->nullable();
            $table->integer('act168')->nullable();
            $table->integer('act169')->nullable();
            $table->integer('act170')->nullable();
            $table->integer('act171')->nullable();
            $table->integer('act172')->nullable();
            $table->integer('act173')->nullable();
            $table->integer('act174')->nullable();
            $table->integer('act175')->nullable();
            $table->integer('act176')->nullable();
            $table->integer('act177')->nullable();
            $table->integer('act178')->nullable();
            $table->integer('act179')->nullable();
            $table->integer('act180')->nullable();
            $table->integer('act181')->nullable();
            $table->integer('act182')->nullable();
            $table->integer('act183')->nullable();
            $table->integer('act184')->nullable();
            $table->integer('act185')->nullable();
            $table->integer('act186')->nullable();
            $table->integer('act187')->nullable();
            $table->integer('act188')->nullable();
            $table->integer('act189')->nullable();
            $table->integer('act190')->nullable();
            $table->integer('act191')->nullable();
            $table->integer('act192')->nullable();
            $table->integer('act193')->nullable();
            $table->integer('act194')->nullable();
            $table->integer('act195')->nullable();
            $table->integer('act196')->nullable();
            $table->integer('act197')->nullable();
            $table->integer('act198')->nullable();
            $table->integer('act199')->nullable();
            $table->integer('act200')->nullable();
            $table->integer('act201')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kankens');
    }
}
